### ISSUE TITLE
Mobile Treat Detail | Reviews break grid

### ISSUE THREAD

**Issue by lizbethsteele** [CKMKDigital/Zukes#33]
Jay – I have tried adding max width, width, etc and nothing so far has worked for keeping the amazon iframe in the grid. Any ideas? I did some quick research and found a lot of people having this issue with amazon iframes not responding on mobile, but no fixes.

**Comment by DevStL** [comment]
we don't have any control over the width of the content in the amazon reviews iframe. so on mobile, the user may have to scroll to the sides. ideally we will have bazaarvoice replace the amazon reviews for phase 2.

**Comment by DevStL** [comment]
should we hide the product image next to the amazon reviews, since the reviews are for all recipes in the product - not a specific recipe?
